version: '3.7'
services:
  aider:
    build:
      context: .
      dockerfile: ./Dockerfile  
    volumes:
      # Uncomment for aider development:
      - .:/src

      # The project that we work on:
      - ${AIDER_WORKDIR}:${AIDER_WORKDIR_CONTAINER}

      # Make local user's git config available in 
      # the container but readonly:
      - ${HOME}/.gitconfig:/home/appuser/.gitconfig:ro

    working_dir: ${AIDER_WORKDIR_CONTAINER}

    command: tail -f /dev/null
    env_file:
      # Remember to set AIDER_WORKDIR and OPENAI_API_KEY:
      - .env
